export const categoryIcons: { [key: string]: string } = {
  "animals": "🐘",
  "art": "🎨",
  "architecture": "🏛️",
  "astronomy": "🪐",
  "businessAndFinance": "💼",
  "comics": "💥",
  "famousLandmarks": "🗽",
  "foodAndDrink": "🍽️",
  "generalKnowledge": "🧠",
  "geography": "🌍",
  "healthAndMedicine": "⚕️",
  "history": "📜",
  "inventions": "💡",
  "islamReligion": "🕌",
  "literature": "📚",
  "mathematics": "🧮",
  "movies": "🎬",
  "music": "🎵",
  "mythology": "🦄",
  "philosophy": "🤔",
  "politics": "🗳️",
  "programming": "🧑‍💻",
  "scienceAndNature": "🧬",
  "sports": "🏆",
  "technology": "💻",
  "television": "📺",
  "videoGames": "🎮",
  "worldCuisine": "🍜",
  "worldReligions": "🙏",
};